version: '3.8'

services:
  frontend:
    build:
      context: ./oupharmacyapp
    ports: # Vite port: 5173 => 3000:80 Nginx
      - "3000:80" 

  backend:
    build:
      context: ./OUPharmacyManagementApp
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DEBUG: "True"
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_ORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    env_file:
      - ./OUPharmacyManagementApp/.env 

  db:
    image: mysql:8.0
    env_file: 
      ./OUPharmacyManagementApp/.env
    container_name: mysql_container
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
