# Generated by Django 4.0.3 on 2023-03-25 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_commoncity_commondistrict_examination_reminder_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commoncity',
            name='active',
        ),
        migrations.RemoveField(
            model_name='commondistrict',
            name='active',
        ),
        migrations.RemoveField(
            model_name='commonlocation',
            name='active',
        ),
    ]
