# Generated by Django 4.0.3 on 2023-05-19 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_remove_user_address_user_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.patient'),
        ),
    ]
