# Generated by Django 4.0.3 on 2024-01-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_doctoravailability_examination_doctor_availability'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='diagnosis',
            options={'verbose_name_plural': 'Diagnosis'},
        ),
        migrations.AddField(
            model_name='medicineunit',
            name='packaging',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
